enum Color {
  BLACK = "black",
  WHITE = "white",
  GRAY = "gray",
  NAVY_BLUE = "navy blue",
  RED = "red",
  BLUE = "blue",
  GREEN = "green",
  OLIVE = "olive",
  PURPLE = "purple",
  PINK = "pink",
  YELLOW = "yellow",
  ORANGE = "orange",
  BROWN = "brown",
  MAROON = "maroon",
  BEIGE = "beige",
  TURQUOISE = "turquoise",
  TEAL = "teal",
  BURGUNDY = "burgundy",
  KHAKI = "khaki",
  LILAC = "lilac",
}
export default Color;
